# Summary
##### Create list - [] and range
##### Using []
##### Slicing lists
##### Tuples 
##### Function / Packages
##### Numpy and Arrays
##### Slicing arrays

---

# List

In [1]:
l = [3,6,9,12,15]
type(l)

list

In [2]:
ml = ["hello",24,True,55.3]
ml

['hello', 24, True, 55.3]

In [3]:
lol = ["list of lists",l]
lol

['list of lists', [3, 6, 9, 12, 15]]

# Range

In [4]:
a = list(range(20))
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [5]:
b = list(range(2,20))
b

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [6]:
c = list(range(2,20,2))
c

[2, 4, 6, 8, 10, 12, 14, 16, 18]

---

# Using [] 

###### 0 | 1 | 2 | 3 | 4
###### a | b | c | d | e

In [7]:
w = ['a','b','c','d','e']
w

['a', 'b', 'c', 'd', 'e']

In [8]:
w[0]

'a'

In [9]:
w[-5]

'a'

In [10]:
w[len(w)-1]

'e'

In [11]:
w[-1]

'e'

In [12]:
w[2] = 'z'
w

['a', 'b', 'z', 'd', 'e']

---

# Slicing lists

###### 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
###### a | b | c | d | e | f | g | h | i |  j

###### slice[start : end : steps]

In [13]:
l = ['a','b','c','d','e','f','h','i','j']
l

['a', 'b', 'c', 'd', 'e', 'f', 'h', 'i', 'j']

In [14]:
l[:]

['a', 'b', 'c', 'd', 'e', 'f', 'h', 'i', 'j']

In [15]:
l[2:7]

['c', 'd', 'e', 'f', 'h']

In [16]:
l[-8:7]

['b', 'c', 'd', 'e', 'f', 'h']

In [17]:
l[-8:-2]

['b', 'c', 'd', 'e', 'f', 'h']

In [18]:
l[2:]

['c', 'd', 'e', 'f', 'h', 'i', 'j']

In [19]:
l[:7]

['a', 'b', 'c', 'd', 'e', 'f', 'h']

# Steps

In [20]:
l[::2]

['a', 'c', 'e', 'h', 'j']

In [21]:
l[2:7:2]

['c', 'e', 'h']

In [22]:
l[::-1]

['j', 'i', 'h', 'f', 'e', 'd', 'c', 'b', 'a']

In [23]:
l[7:2:-1]

['i', 'h', 'f', 'e', 'd']

---

# Tuples

###### immutable list

In [24]:
t = (345,456,567)
type(t)

tuple

In [25]:
t[1]

456

---

# Functions in Python

In [26]:
a = list(range(20,31))
a

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [27]:
print(a)

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]


In [28]:
len(a)

11

In [29]:
type(a)

list

In [30]:
max(a)

30

In [31]:
min(a)

20

In [32]:
max(1,2,3,4,5)

5

# Packages in Python

###### module - file containing python definitions, functions and statements
###### packages - a collection of related modules. Eg - Numpy, Scipy, ...

###### step 1 - find the package
###### step 2 - install the packages (pip install packagename)
###### step 3 - import the package (import packagename) 

---

# Arrays

###### same type of elements only
###### comes with lot of methods

In [33]:
import numpy as np

In [34]:
l = [123,234,345,456,567]
a = np.array(l)
a

array([123, 234, 345, 456, 567])

In [35]:
ml = ["hello",24,True,55.3]
b = np.array(ml)
b

array(['hello', '24', 'True', '55.3'], 
      dtype='<U5')

In [36]:
a.mean()

345.0

# Slicing

###### Slicing a list creates a copy of the list. Slicing an array creates a view of the array.

###### Numpy creates a view of array and any change in view changes the original array

In [37]:
a[2:]

array([345, 456, 567])

In [38]:
b = a[2:4]
b

array([345, 456])

In [39]:
b[:]=111
b

array([111, 111])

In [40]:
a

array([123, 234, 111, 111, 567])

In [41]:
c = a[0:2].copy()
c

array([123, 234])

In [42]:
c[:]=0
c

array([0, 0])

In [43]:
a

array([123, 234, 111, 111, 567])

---

# Financial Statement Analysis

In [44]:
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [45]:
tax = []
pat = []
for i in range(0,len(revenue)):
    tax.append(round((revenue[i] - expenses[i])*0.3,2))
    pat.append(round((revenue[i] - expenses[i])*0.7,2))

In [46]:
print(pat)

[1765.87, 1337.97, -2595.45, -2040.02, -419.94, 5085.67, 5747.39, 2761.48, 2329.87, -1567.06, 461.72, 8140.68]


In [47]:
pom = []
for i in range(0,len(revenue)):
    pom.append(round((pat[i] / revenue[i])*100,2))

In [48]:
print(pom)

[12.12, 17.59, -30.14, -22.23, -5.21, 62.74, 49.99, 28.28, 22.61, -10.9, 4.31, 52.75]


In [49]:
avg_pro = sum(pat)/len(pat)
max_pro = max(pat)
min_pro = min(pat)

In [50]:
print(avg_pro)
print(max_pro)
print(min_pro)

1750.6816666666666
8140.68
-2595.45


# Good and Bad Months

In [51]:
gdm = []
bdm = []
for i in range(0,len(pat)):
    gdm.append(pat[i] > avg_pro)
    bdm.append(pat[i] < avg_pro)

In [52]:
print(gdm)
print(bdm)

[True, False, False, False, False, True, True, True, True, False, False, True]
[False, True, True, True, True, False, False, False, False, True, True, False]


In [53]:
best_month = []
worst_month = []
for i in range(0,len(pat)):
    best_month.append(pat[i] == max_pro)
    worst_month.append(pat[i] == min_pro)

In [54]:
print(best_month)
print(worst_month)

[False, False, False, False, False, False, False, False, False, False, False, True]
[False, False, True, False, False, False, False, False, False, False, False, False]
